# Generated by Django 4.0.3 on 2022-04-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.CharField(max_length=50, verbose_name='Fecha')),
                ('Categoria', models.CharField(max_length=50, verbose_name='Categoria')),
                ('Importe', models.IntegerField()),
                ('Nota', models.CharField(max_length=50, verbose_name='Nota')),
                ('Tipo_gasto', models.CharField(max_length=50, verbose_name='Tipo de Gasto')),
            ],
        ),
    ]
