# Generated by Django 4.0.3 on 2022-04-06 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGastos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientos',
            old_name='Tipo_gasto',
            new_name='Tipo_movimiento',
        ),
    ]
