# Generated by Django 4.0.3 on 2022-04-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGastos', '0004_alter_movimientos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='Importe',
            field=models.CharField(max_length=50, verbose_name='Categoria'),
        ),
    ]
