# Generated by Django 4.0.3 on 2022-04-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGastos', '0005_alter_movimientos_importe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='Importe',
            field=models.IntegerField(),
        ),
    ]
