# Generated by Django 4.0.3 on 2022-04-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGastos', '0006_alter_movimientos_importe'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('ID_Usuario', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('Contraseña', models.CharField(max_length=20, verbose_name='Contraseña')),
            ],
        ),
    ]
