# Generated by Django 4.0.3 on 2022-04-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGastos', '0008_objetivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='Importe',
            field=models.IntegerField(verbose_name='Importe'),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='Tipo_movimiento',
            field=models.CharField(max_length=50, verbose_name='Tipo_movimiento'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='MontoDelObjetivo',
            field=models.IntegerField(verbose_name='MontoDelObjetivo'),
        ),
    ]
